# Generated by Django 4.2.6 on 2023-11-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(default='system', max_length=20)),
                ('stand_up_reminder', models.BooleanField(default=False)),
                ('break_reminder', models.BooleanField(default=False)),
                ('productivity_reminder', models.BooleanField(default=False)),
                ('positive_feedback_reminder', models.BooleanField(default=False)),
                ('track_fatigue', models.BooleanField(default=False)),
                ('track_other_people', models.BooleanField(default=False)),
                ('track_smartphone', models.BooleanField(default=False)),
                ('tracking_grade', models.FloatField(default=0.7)),
            ],
        ),
    ]
