# Generated by Django 4.2.6 on 2023-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskVueWebAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_workload', models.FloatField(default=0.0)),
                ('tuesday_workload', models.FloatField(default=0.0)),
                ('wednesday_workload', models.FloatField(default=0.0)),
                ('thursday_workload', models.FloatField(default=0.0)),
                ('friday_workload', models.FloatField(default=0.0)),
                ('saturday_workload', models.FloatField(default=0.0)),
                ('sunday_workload', models.FloatField(default=0.0)),
                ('monday_breaks', models.FloatField(default=0.0)),
                ('tuesday_breaks', models.FloatField(default=0.0)),
                ('wednesday_breaks', models.FloatField(default=0.0)),
                ('thursday_breaks', models.FloatField(default=0.0)),
                ('friday_breaks', models.FloatField(default=0.0)),
                ('saturday_breaks', models.FloatField(default=0.0)),
                ('sunday_breaks', models.FloatField(default=0.0)),
                ('monday_distractions', models.FloatField(default=0.0)),
                ('tuesday_distractions', models.FloatField(default=0.0)),
                ('wednesday_distractions', models.FloatField(default=0.0)),
                ('thursday_distractions', models.FloatField(default=0.0)),
                ('friday_distractions', models.FloatField(default=0.0)),
                ('saturday_distractions', models.FloatField(default=0.0)),
                ('sunday_distractions', models.FloatField(default=0.0)),
            ],
        ),
    ]
