# Generated by Django 4.2.6 on 2023-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskVueWebAPI', '0005_usersettings_track_key_mouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('process_flow', models.TextField()),
            ],
        ),
    ]
