# Generated by Django 4.2.6 on 2024-01-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskVueWebAPI', '0007_usersettings_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='break_reminder',
            new_name='track_distraction',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='positive_feedback_reminder',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='productivity_reminder',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='stand_up_reminder',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='track_key_mouse',
        ),
    ]
